### ISSUE TITLE
súgó?

### ISSUE THREAD

**Issue by falu** [zsiki/GeoEasy#1]
A súgó fájlok nem lettek publikusak?
A [helpgeo.tcl](https://github.com/zsiki/GeoEasy/blob/master/helpgeo.tcl) keresi a fájlokat, de sehogy sem találja, ezért hibaüzenetet dob.

**Comment by zsiki** [comment]
A súgó fájlok csak magyarul vannak meg egyelőre, a digikom honlapról a pdf változat letölthető (még az előző változathoz valamit az újdonságok felsorolása is).
A telepítési útmutatót már elkészítettem rst formátumban. Nem akarom folytatni a html-ben folytatni a dokumentálást. A következő a lépésről-lépésre leírás lesz...
