### ISSUE TITLE
Datum transfer

### ISSUE THREAD

**Issue by Tuchband** [zsiki/GeoEasy#107]
Dear Developers
GeoEasy has a precise transformation between coordinate systems, but we have to take care about the elevation datums, or it would be good, if you can decide which datum you want to transform. While the kml output is created well in WGS84, so the latitude and longitude are good, the elevation will be computed above the ellipsoid correctly. If you want to check the kml with Google Earth for example, the elevations will be "bad", because they use the EGM96 geoid as a reference. Therefore it would be nice, that during the kml export you could choose, that you still need the elevation above the WGS84 ellipsoid, or above the geoid.
Thanks!

**Comment by zvezdochiot** [comment]
>EGM96 geoid
???
No geodesy.

**Comment by zsiki** [comment]
There are some possible solutions:

1. Original elevations (amsl) are preserved, only 2D transformation is used
2. A global vertical datum shift can be input to change original elevations 
3. EGM96 model is used to interpolate undulations and the elevations above ellipsoid are corrected by the interpolated undulations

The first two solutions are more or less correct for small areas (few square km). The third one can be used globally, but 5 MB grid is used for interpolation. See: http://earth-info.nga.mil/GandG/wgs84/gravitymod/egm96/egm96.html
