### ISSUE TITLE
Fieldbook import for network and level adjustment

### ISSUE THREAD

**Issue by maksa6** [zsiki/GeoEasy#112]
I have a problem when importing your levelling.dmp, I just get the number of the station and the reference point. Can I create a dmp file for angles and lengths from the total station, since I have a south total station, so I would have to import it manually
![problem import](https://user-images.githubusercontent.com/51032707/58374128-d500b400-7f38-11e9-925a-0fcc70a39fc2.png)

**Comment by zsiki** [comment]
leveling.dmp contains height differences and distances of levelling lines. Change the mask to levelling. Please read the **Leveling network adjustment** chapter in Step by step guide:
https://github.com/zsiki/GeoEasy/blob/master/doc/step_by_step.rst
You can create dump file for total station observations too. Try to export test1.geo into test1.dmp.
Examine the content of the dump file and try to load it.

**Comment by maksa6** [comment]
i have try to import leveling.dmp with your step by step, but when I remove Horizontal angle, Vertical angle, lope distance, signal height,instrument height and add horizontal distance and Height diff. leveling, I only get station number and point number in fieldbook, like on image.
And when i add horizontal distance and Height diff there is in {horizontal distance} {Height diff.levelling} like in picture,what i am doing wrong.
And I have put separators (one space).
It looks like I can not change any of the column names, because when I change get cornered brackets and do not insert me data
![problem import](https://user-images.githubusercontent.com/51032707/58760972-08e26780-853f-11e9-8bf9-916dfcb18426.png)

**Comment by zsiki** [comment]
Unfortunately I didn't check carefully your attached image :(, the curly brackets cause the problem.
There was a bug in the code, see https://github.com/zsiki/GeoEasy/issues/102.
Please install the latest version 3.1.1

**Comment by maksa6** [comment]
thanks, now is working
