### ISSUE TITLE
circle regression 

### ISSUE THREAD

**Issue by zsiki** [zsiki/GeoEasy#127]
some datesets give strange results, see fogadoakna_Alaplemez, Reported by Csaba Égető.

**Comment by zvezdochiot** [comment]
See also: https://github.com/Geo-Linux-Calculations/gnumeric-ols/blob/master/spreadsheets/ols-circle.gnumeric

**Comment by zsiki** [comment]
Very large coordinates made the algorithm unstable. Offset is used to reduce the coordinate values.
