### ISSUE TITLE
Save graphic window to image file

### ISSUE THREAD

**Issue by zsiki** [zsiki/GeoEasy#136]

**Comment by zvezdochiot** [comment]
Repeat:
* #30 
* #44

**Comment by zsiki** [comment]
Export to png added to Linux version only.

**Comment by zvezdochiot** [comment]
@zsiki say:
>Export to png added to Linux version only.

Maybe use `gama-local`?:
```sh
gama-local temp.gkf --svg output.svg
```

**Comment by zsiki** [comment]
The SVG output (error ellipses) was implemented in GeoEasy. You can set it in the Adjusment parameters dialogue. It is a checkbox (SVG error ellipses).
