### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by Tuchband** [zsiki/GeoEasy#14]
Egy észrevétel a 3.00 windows binárissal kapcsolatban, hogy unistall nem hajtódik végre, és a programok és szolgáltatások közül sem tűnik el, és könnyú eszközökkel eltávolítani sem tudom. Nem tudom, hogy a 3.02-es is ilyen-e, de ha windows telepítőt nem babráltad, akkor valószínűleg ugyanez a helyzet.

**Comment by zsiki** [comment]
Please  use the latest release to report bugs/issues. Bug fixes are not ported back to old versions.
I've tested 3.0.2 on WIndows 10:

- installation folder removed
- desktop icon removed
- GeoEasy program removed from the start menu

The uninstall and GeoEasy homepage left in the menu (this should be removed too)

Did you install/uninstall GeoEasy as administrator user?

**Comment by zsiki** [comment]
In the development version (V3.0.3) installation kit has been repaired, uninstall and homepage menu items are removed by uninstaller.
