### ISSUE TITLE
Trigonometrical node

### ISSUE THREAD

**Issue by zsiki** [zsiki/GeoEasy#140]
Trigonometrical node calculation sets the elevation of the node from the first free trigonometrical line, following lines are calculated as non free line.
Reported by Gábor Brolly.

**Comment by zvezdochiot** [comment]
Hi @zsiki .

I believe that such "hidden problems" stem from inadequate test material.  
https://github.com/zsiki/GeoEasy/blob/master/src/demodata/test1.geo does not contain enough networks for testing.  
The solution to most of the "problems" is carried out by elaborating complex networks.

**Comment by zsiki** [comment]
Volunteers are welcome to create test data sets
