### ISSUE TITLE
i18n: Russian: 2020

### ISSUE THREAD

**Issue by zvezdochiot** [zsiki/GeoEasy#143]
Hi @zsiki .

Take the current https://github.com/Geo-Linux-Calculations/GeoEasy/blob/master/src/i18n/geo_easy.rus for your repository.

**Comment by zsiki** [comment]
why didn't you send a pull request?

**Comment by zvezdochiot** [comment]
@zsiki say:
>why didn't you send a pull request?

I cant. Our git-histories are incompatible.

**Comment by zsiki** [comment]
Done.
Please remove ;#TODO at the end of the line after translation. It is a marker for the translator.

**Comment by zvezdochiot** [comment]
@zsiki say:
>Please remove ;#TODO

OK,

**Comment by zvezdochiot** [comment]
Hi @zsiki .

For the next release, you can use a utility to help you with proofreading:
```sh
diction you.txt
```

**Comment by zvezdochiot** [comment]
Hi @zsiki .

Repeat. (remove complite TODO)
