### ISSUE TITLE
ComEasy - Error when executing Help > Help ...

### ISSUE THREAD

**Issue by XRolland** [zsiki/GeoEasy#145]
In ComEasy, we've got an error message  when executing Help > Help ...

`Error:wrong # args: should be "GeoHelp"
`

![image](https://user-images.githubusercontent.com/16253809/103284237-f9592800-49da-11eb-89a5-427e1625cc68.png)

Pushing on the **Details** button shows:
```
wrong # args: should be "GeoHelp"
wrong # args: should be "GeoHelp"
    while executing
"GeoHelp ComEasy.html"
    (menu invoke)
```
Found with GeoEasy 3.1.2, windows portable binary, running on Windows 10.

**Comment by zvezdochiot** [comment]
https://github.com/zsiki/GeoEasy/blob/cab09d84d849c243eb9f26111201badcf4565932/src/com_easy.tcl#L66

**Comment by XRolland** [comment]
Is it because there's not any help html file?
Is it possible to use url instead , linking to something as:
- https://github.com/zsiki/GeoEasy/tree/master/doc
- https://github.com/zsiki/GeoEasy/wiki

**Comment by zvezdochiot** [comment]
@XRolland say:
>Is it possible to use url instead , linking to something as:

No. Wait. @zsiki has reserved this. It will determine how to organize the help and correct it.

**Comment by zvezdochiot** [comment]
@XRolland , you not watch: https://github.com/zsiki/GeoEasy/watchers

**Comment by XRolland** [comment]
@zvezdochiot I don't use ComEazy anywhere. I was checking my localization file (early work, work in progress) when I found this problem.
But why did you link #64 issue? I don't understand as it seems to be not data related.

**Comment by zvezdochiot** [comment]
@XRolland say:
>But why did you link #64 issue? I don't understand as it seems to be not data related.

This is due to the fact that the project needs help. Both in reference material and test data. Participate, contribute.

**Comment by XRolland** [comment]
As everywhere in FLOSS world :wink: Reporting is a contribution.
I'm not a coder. And I'm not able to be everywhere at the same time.

**Comment by zvezdochiot** [comment]
@XRolland say:
>I'm not a coder. And I'm not able to be everywhere at the same time.

No need to program. @zsiki does an excellent job with this. We need test data from devices in the specified formats.

**Comment by zsiki** [comment]
@XRolland thank you reporting this bug.  I accept your idea to display link to doc and wiki on GitHub.

Some years ago I had an idea to have a context sensitive help, but I couldn't realize it so far...
