### ISSUE TITLE
GeoEasy - ComEasy - Error when executing File > Save Parameters ...

### ISSUE THREAD

**Issue by XRolland** [zsiki/GeoEasy#146]
In GeoEasy, we've got an error message  when executing File > Save Parameters ...
```
Error 
Variable not found regLineClose
```
Settings are however stored:
```
2020.12.29 15:22 - Parameters saved to geo_easy.msk
previous parameters are backed up into geo_easy.msk.bak.
```
Found with GeoEasy 3.1.2, windows portable binary, running on Windows 10.

**Comment by zvezdochiot** [comment]
In 3.1.2:
```tcl
	global maskRows
	global regLineStart regLineCont regLineEnd regLine
```
In 3.1.3:
https://github.com/zsiki/GeoEasy/blob/7bcac5f1f1d2715ebaeafc31bb1dfdab4c0bd047/src/loadgeo.tcl#L1870-L1871

**Comment by XRolland** [comment]
Oh 💩 ! I thaught I had downloaded the last binary! 
Thanks for your  help. I  confirmed, after checking same kind of binary (portable win, 32 and 64 arch).

Sorry for the outdated report. I close the issue.
