### ISSUE TITLE
Can't open SurvPC rw5 file

### ISSUE THREAD

**Issue by XRolland** [zsiki/GeoEasy#147]
Hello,

When I try to open a RW5 file, I got this error:

**Application error**
Error:invalid command name "SurvCe"
```
invalid command name "SurvCe"
invalid command name "SurvCe"
    while executing
"SurvCe $fn"
    ("*.rw5" arm line 2)
    invoked from within
"switch -glob [string tolower $fn] {
				*.job {
					set res [Geodimeter $fn]
					if {$res == 0} {	;# try to load are too
						set fn1 [file rootnam..."
    (procedure "MenuLoad" line 32)
    invoked from within
"MenuLoad ."
    (menu invoke)
```

I tried with many RW5 files, all produced with SurvPC 6.x
Do you want some data to test?

Happens with GeoEasy64 on Windows 10.

**Comment by zsiki** [comment]
Unfortunately I made a mistake during packaging. A source module wan not included :(
I'll create a new development version soon to correct the mistake.

Test data are always welcome! Thanks.

**Comment by XRolland** [comment]
3.1.4 tested on win 10 : it's ok. Thank you for the fix.

Another problem: signal height is not loaded (no problem for the instrument height). Signal height for the equivalent Sokkia SDR is loaded without pb. Maybe it's better that I'll open a new issue?

**Comment by zsiki** [comment]
Yes, please open a new issue or reopen this one. It would be nice if you could attache sample rw5 file(s) with signal height. 
I've checked and I've found an error in my code. The  signal height (HR code in rw5) was not added to the observation record. Anyway some test data would help.

**Comment by zsiki** [comment]
Please test the new development release, target height should be read from rw5  files.
http://digikom.hu/english/geo_easy_e.html

**Comment by XRolland** [comment]
It works! Thanks you Zlotan 👍

**Comment by XRolland** [comment]
Argh I answered too quick... observations are OK, but coordinates failed.
I'll open a bug report as it is off-subject here and as this one is closed.

**Comment by zsiki** [comment]
Can you send me your rw5 file?

**Comment by XRolland** [comment]
I opened the #149 issue about this problem. Raw files are included
