### ISSUE TITLE
Opening coordinates listing fails with "can't read geoEasyMsg(menuCooSwapEN): no such element in array"

### ISSUE THREAD

**Issue by XRolland** [zsiki/GeoEasy#149]
After loading a RW5 (or a SDR one) file, observations window and observations parameters  opens with no problem, but coordinates window fail to open with this warning message:
**`Application Error`** 
```
can't read "geoEasyMsg(menuCooSwapEN)": no such element in array
can't read "geoEasyMsg(menuCooSwapEN)": no such element in array
    while executing
"$mnu.command add command -label $geoEasyMsg(menuCooSwapEN)  -command "Swap2 ${fn} EN; CooFillMask $fn \$maskPos($w) $w""
    (procedure "GeoMask" line 82)
    invoked from within
"GeoMask $m $fn "_coo""
    (procedure "EditCoo" line 16)
    invoked from within
"EditCoo veuillis_dg_s01"
    (menu invoke)
```

Same error occurs with a SDR file. Both raw files are joined to this report.
[V_Dg_S01.zip](https://github.com/zsiki/GeoEasy/files/5892801/V_Dg_S01.zip)

It occurs with:
 - GeoEasy 3.14 dev (2021.01.28), as portables x64 binaries on Win10

It doesn't occur with:
 - GeoEasy 3.12 & 3.13, as portables x64 binaries on Win10, with the SDR raw file

**Comment by XRolland** [comment]
SDR file in the first send was corrupted. I fixed it.

**Comment by zsiki** [comment]
It is a packaging issue. Unfortunately I added wrong message files in i18n folder. A quick and dirty solution for you (till I make a new development release) to download the message files from the i18n folder from GitHub.
I could load your rw5 file but an error reported on line 9 for your sdr file what I have to check.

Thank you for your feedback. I will make a new development release during the weekend

**Comment by XRolland** [comment]
> I could load your rw5 file but an error reported on line 9 for your sdr file what I have to check.
Try to download the zip file again,a s said upper, the SDR file was corrupted when I included it at the first time.

**Comment by zsiki** [comment]
Sdr loader can read the corrected sdr file.

**Comment by zsiki** [comment]
New development version available on the http://digikom.hu/english/geo_easy_e.html
