### ISSUE TITLE
Resection (SDR)? 

### ISSUE THREAD

**Issue by zvezdochiot** [zsiki/GeoEasy#150]
GeoEasy 3.1.3

Source: 20210205-3st.sdr ([gnu-gama-3st-2K.zip](https://github.com/zsiki/GeoEasy/files/5936774/gnu-gama-3st-2K.zip))

![sheme](https://i114.fastpic.ru/big/2021/0206/74/b62bf33639fac50ca3e663f17b449074.png)

Construction network from Resection (3 stations). Cannot calculate or export to GNU Gama. GNU Gama itself processes the data.

See also: https://geodesist.ru/threads/programmy-dlja-uravnivanija-linejno-uglovyx-setej.72942/page-2#post-992493

**Comment by zsiki** [comment]
Does it solve? https://github.com/zsiki/GeoEasy/commit/c260dc88f8ef19fc92feee0be501ea1996480a7c
Before this commit you have to save the SDR input to GeoEasy format and load that.

**Comment by zvezdochiot** [comment]
Hi @zsiki .

I can't check now. I'll try on Monday.

**Comment by zvezdochiot** [comment]
@zsiki say:
>Does it solve?

`Calculate -> Orientations`  
Info: `Orientation cannot be calculated for any station`

**Comment by zvezdochiot** [comment]
`GNU Gama Export` ok.

**Comment by zsiki** [comment]
I loaded 20210205-3st.sdr and selected Calculate/Orientations and I got:

```
2021.02.08 11:17 - GeoEasy started
Station number: ST1
Station   Collimation     Index Distance T.height
Target        error       error   diff.    diff.
G3            0-00-08 -  0-00-06 0.0020  0.000
G4            0-00-05 -  0-00-05 0.0010  0.000
G5            0-00-10 -  0-00-05 0.0040  0.000
G8         -  0-00-00 -  0-00-05 0.0060  0.000
G10        -  0-00-05 -  0-00-09 0.0040  0.000
M1            0-00-08 -  0-00-05 0.0020  0.000
M2            0-00-08 -  0-00-03 0.0010  0.000
M3            0-00-08 -  0-00-07 0.0020  0.000
M4            0-00-06 -  0-00-07 0.0060  0.000
M6            0-00-04 -  0-00-09 0.0060  0.000
D1            0-00-04 -  0-00-03 0.0030  0.000
Station number: ST2
M4            0-00-04 -  0-00-01 0.0030  0.000
G3            0-00-03 -  0-00-04 0.0040  0.000
G10           0-00-03 -  0-00-12 0.0010  0.000
G19           0-00-05 -  0-00-07 0.0080  0.000
M1            0-00-07 -  0-00-09 0.0020  0.000
M2            0-00-06 -  0-00-06 0.0030  0.000
M3            0-00-06 -  0-00-05 0.0020  0.000
M5            0-00-10 -  0-00-06 0.0010  0.000
M6            0-00-06 -  0-00-08 0.0000  0.000
M7            0-00-04 -  0-00-07 0.0020  0.000
M8            0-00-04 -  0-00-06 0.0030  0.000
M9            0-00-03 -  0-00-05 0.0030  0.000
M10           0-00-07 -  0-00-05 0.0010  0.000
MM9           0-00-05 -  0-00-05 0.0030  0.000
D1            0-00-07 -  0-00-08 0.0080  0.000
Station number: ST3
G10           0-00-05 -  0-00-07 0.0040  0.000
G19           0-00-05 -  0-00-01 0.0030  0.000
M4         -  0-00-05 -  0-00-06 0.0030  0.000
M5            0-00-04 -  0-00-04 0.0020  0.000
M6            0-00-06 -  0-00-05 0.0040  0.000
M7            0-00-13 -  0-00-05 0.0010  0.000
M8            0-00-03 -  0-00-08 0.0020  0.000
M9            0-00-05 -  0-00-02 0.0010  0.000
M10           0-00-05 -  0-00-03 0.0030  0.000
MM9           0-00-05 -  0-00-03 0.0010  0.000
2021.02.08 11:17 - /home/siki/GeoEasy/data/zvezdochiot/20210205-3st.sdr data set loaded

2021.02.08 11:17 - Orientation - ST1
Point num  Code         Direction    Bearing   Orient ang   Distance   e" e"max   E(m)
G3                      234-07-12    70-00-06   195-52-54   1406267.028 290986    0 1983879.952
D1                       35-45-03    70-00-09    34-15-05   1406381.400 -290882    0 -1983333.932
Average orientation angle                       115-03-08

2021.02.08 11:18 - Orientation - ST2
Point num  Code         Direction    Bearing   Orient ang   Distance   e" e"max   E(m)
G3                        7-08-09    70-49-38    63-41-29   1396724.201 -407693    0 -2760698.761
MM9                     184-23-58    70-49-30   246-25-32   1396868.432 250150    0 1694071.458
D1                      254-54-46    70-49-40   175-54-54   1396838.837 -3688    0 -24975.604
Average orientation angle                       176-56-22

2021.02.08 11:18 - Orientation - ST3
Point num  Code         Direction    Bearing   Orient ang   Distance   e" e"max   E(m)
MM9                       0-07-42    69-59-34    69-51-52   1405292.075    0    0    0.000
Average orientation angle                        69-51-52
```
Some coordinates are false but calculation works.

**Comment by zvezdochiot** [comment]
@zsiki say:
>Some coordinates are false but calculation works.

Put ST1, ST2 and ST3 in "coarse". Does not work.

**Comment by zsiki** [comment]
What does "coarse" mean in this case. If you erase the coordinates of ST1, ST2, ST3 or make them preliminary, no way to calculate orientation on these points without the station coordinates.
On the other hand this is not a network, no sense to use network adjustment.

**Comment by zvezdochiot** [comment]
@zsiki say:
>On the other hand this is not a network, no sense to use network adjustment.

From the classical point of view, it is not a network. But! This is precisely the modern standard serif construction network. Ce-La-Vi.

**Comment by zsiki** [comment]
It may be modern but not rigid enough. I would make observations between ST1-ST2 and ST2-ST3.

**Comment by zvezdochiot** [comment]
@zsiki say:
>It may be modern but not rigid enough. I would make observations between ST1-ST2 and ST2-ST3.

In most cases this is not possible.

PS: Is it possible, when exporting to GNU Gama, not to write "rough" coordinates to points. Then GeoEasy would at least be a converter for such tasks.
