### ISSUE TITLE
GNU Gama Export?

### ISSUE THREAD

**Issue by zvezdochiot** [zsiki/GeoEasy#151]
Maybe when exporting to GNU Gama, not to write "rough" coordinates to points? Then GeoEasy would at least be a converter for such tasks (https://github.com/zsiki/GeoEasy/issues/150).
https://github.com/zsiki/GeoEasy/blob/dca355d11fd97baedfa555b7e1782f68ed6b4d8a/src/xmlgeo.tcl#L1018-L1028
to
```tcl
			if {$pcooopt == "noval"} {
				puts $xml "<point id=\"$pn\" adj=\"$adjxy\" />"
			} else {
				set pcoo [GetCoord $pn {38 37}]
				if {$pcoo == ""} {
					set pcoo [GetCoord $pn {138 137}]
					if {$pcoo == ""} {
						puts $xml "<point id=\"$pn\" adj=\"$adjxy\" />"
					} else {
						puts $xml "<point id=\"$pn\" y=\"[format %.${decimals}f [GetVal 138 $pcoo]]\" x=\"[format %.${decimals}f [GetVal 137 $pcoo]]\" adj=\"$adjxy\" />"
					}
				} else {
					puts $xml "<point id=\"$pn\" y=\"[format %.${decimals}f [GetVal 38 $pcoo]]\" x=\"[format %.${decimals}f [GetVal 37 $pcoo]]\" adj=\"$adjxy\" />"
				}
			}
```

**Comment by zvezdochiot** [comment]
Hi @zsiki .

Calculate "Preliminary coordinates":
![prel](https://i114.fastpic.ru/big/2021/0215/cf/9258c63077f4faef6db42205004ef8cf.png)
Remove value "Preliminary coordinates":
![noval](https://i114.fastpic.ru/big/2021/0215/3f/f0312bd260eed3c36cbd33d7a474483f.png)
"GNU Gama export ..."
![gama-export](https://i114.fastpic.ru/big/2021/0215/60/899ef76b888d4f2ee0f9865c7b75b160.png)
There are no undefined points in the list!

**Comment by zvezdochiot** [comment]
Hi @zsiki .

See https://github.com/Geo-Linux-Calculations/GeoEasy/commit/cd93101fab44282792fe4b9551a69f0e894b12a6

**Comment by zsiki** [comment]
GeoEasy not only exports data to GNU Gama, it makes extensive checks on observations and preliminary coordinates. It helps early error detection of some type of errors (for example typo in point id).
From my point of view it is the normal behavior.
