### ISSUE TITLE
Angles in minute/second of Arc when everything set to Tachymeter_gon

### ISSUE THREAD

**Issue by Bustebartepinn** [zsiki/GeoEasy#155]
In main window->File->Other parameters i have set it to tachymeter_gon
In main window->Edit->Observations  Command->mask i have set it to cachymeter_gon
My inputfile is in gon.

Still the Calculation result show a mix of gon and minute/second of arc.
Any settings i have missed, or is this a bug?

Using version 3.1.3

Have just tested a quick export (save as) and there is minute/second of arc there also when my input is gon.

**Comment by Bustebartepinn** [comment]
For some reason my Calculation window now show only gon.
But my popup warning message when doing horisontal network adjustment, that show too large angle between two points show minute/second of arc. 
And save as Fieldbook, saves it also as minute/second of arc.

**Comment by zsiki** [comment]
When you change the mask to tahimeter_gon it will only change units in the field-book window. The calculation results are written in DMS independent from this (except network adjustment output). The field-book uses radians always if you save it to a .geo file. We can say it is a feature or it is a bug.
The angle units of the input file (not in the case of .geo) is detected if it is possible.

Can you send me an example where gons and DMS are mixed in the output?

I suppose you initiate a feature request to set the output angle units (and distance/coordinate units).
It could be a nice enhancement to GeoEasy, we could remove different masks for DMS, gons, feet, meter.

Summarizing your feature request:

- New fields in calculation parameters to set angle and distance units globally.
- Masks and the calculation results use the globally set units.
- Tahimeter_deg, Tahimeter_gon, tahimeter_feet are not necessary after the changes above.

Do you agree?

**Comment by Bustebartepinn** [comment]
> Summarizing your feature request:
> 
> New fields in calculation parameters to set angle and distance units globally.
> Masks and the calculation results use the globally set units.
> Tahimeter_deg, Tahimeter_gon, tahimeter_feet are not necessary after the changes above.
> Do you agree?

Yes a global setting like this sounds like it will fix the issue.

**Comment by zsiki** [comment]
I started to change the code, I'll release a new beta in few day.

**Comment by XRolland** [comment]
Nice improvement. Thanks for your work.
