### ISSUE TITLE
Possibility to have observations deactivated

### ISSUE THREAD

**Issue by Bustebartepinn** [zsiki/GeoEasy#156]
When trying to figure out what measurement is the poor one, could it be possible to set observations passive/active so they are not included in calculations? 
This can help when trying to find the lesser accurate measurements. 
If i delete the observation i have to import the file again if i deleted the wrong one.

**Comment by zvezdochiot** [comment]
@Bustebartepinn say:
>When trying to figure out what measurement is the poor one

A similar scheme is used in RGS. Only there each measurement is cyclically turned off, without operator intervention. As a result, only one "worst" measurement is displayed.

**Comment by zsiki** [comment]
I usually change the name of the point of the outlaying observations. It is another feature request I think. It is a bit complicated if more observations (direction, distance, zenith) are in the same record of the field-book. All fields should have enable/disable checkbox.
Where this feature is important for you? I suppose it is during network adjustment.
I have two ideas to solve this:

- automatic blunder removal in network adjustment
- extra field state for observation fields (as you can set horizontal distance, slope distance) skipped mean direction/distance/zenith

The first one is a solution only for network adjustments, the second could be solution for all calculations.

**Comment by zvezdochiot** [comment]
@zsiki say:
>automatic blunder removal in network adjustment

Warning! It's UB!

**Comment by Bustebartepinn** [comment]
> extra field state for observation fields (as you can set horizontal distance, slope distance) 
> skipped mean direction/distance/zenith

This would mean checkboxes or rightclick option to enable/disable an observation?

I think this would be more interesting to implemen. Then you can force a option into the calculations, rather than than relying on a automated function. Mostly for testing/identifying poor observations.

**Comment by zsiki** [comment]
@zvezdochiot, automatic blunder removal doesn't mean to erase the observation, it means not to consider in the adjustment.

**Comment by zvezdochiot** [comment]
@zsiki say:
>it means not to consider in the adjustment.

⚠️ It's UB!

**Comment by zsiki** [comment]
@Bustebartepinn, a checkbox beside all observations would be a killer for the GUI. I propose to add a 'do not use' type for observed values (mean direction, zenith, slope/horizontal distance, height difference). When you right click on a field in the field-book on the top of the context menu there may be some option to change the type of the value, for example slope distance/horizontal distance. It would be much easier to implement a new option "do not use" there. It wouldn't change much of the GUI.
