### ISSUE TITLE
Swapped X and Y coordinates in gamma adjustment

### ISSUE THREAD

**Issue by hblGP** [zsiki/GeoEasy#158]
Hi, 

When doing an 3D/horizontal adjustment I can see that in the resulting log file, the X and Y coordinates has been swapped around. I think this is mainly an error in the log file as the coordinates are correctly updated, see attached image.

![swapped_x_y](https://user-images.githubusercontent.com/60741008/117429313-3902c400-af27-11eb-9666-2831008af672.PNG)

**Comment by zvezdochiot** [comment]
@hblGP say:
>the X and Y coordinates has been swapped around. 

???  
Easting - who is this [X/Y]?  
Northing - who is this [X/Y]?

**Comment by zsiki** [comment]
Gnu Gama uses the surveyors' coordinate system (as we do in Hungary or Germany) Y is easting and X is northing. The long log message is generated by GNU Gama, GeoEasy only displays it. So I can't solve it. You may ask GNU Gama developers ...

**Comment by hblGP** [comment]
@zsiki Thank you for the explanation, of course that is the case. I've never worked with a left-handed coordinate system and didn't know that there may be different conventions for determining which direction the x and y coordinates goes. You get smarter every day.

**Comment by zvezdochiot** [comment]
@hblGP say:
>I've never worked with a left-handed coordinate system and didn't know that there may be different conventions for determining which direction the x and y coordinates goes.

Made in Russia.
