### ISSUE TITLE
Correction to the zenith angle for R?

### ISSUE THREAD

**Issue by zvezdochiot** [zsiki/GeoEasy#165]
Hi @zsiki .

Subj.

https://github.com/zsiki/GeoEasy/blob/b1bd171039274157195c0742b4db28445ad28173/src/calcgeo.tcl#L268-L269
Aligning the zenith to the median plumb line: 
```tcl
if {[expr {abs($R)}] > 1e-4} {
    set dZR [expr { $d / $R / 2 }] # R = 6370009.0 m, dZR in radians.
}
```
See also https://github.com/Geo-Linux-Calculations/geofindkey/commit/0fa0357bd718dea087704ceb291c141eb80662f2

PS: The dZR correction is: 
* for d = 250 m - 4";
* for d = 500 m - 8";
* for d = 1000 m - 16";

**Comment by zsiki** [comment]
It is considered as the effect of refraction and Earth curvature. You can turn it on/off in the Calculation parameters dialog "Calculate refraction and Erth curvature" (refr variable). It is used only for distance longer than 400 meters for trigonometric height calculation.

**Comment by zvezdochiot** [comment]
Hi @zsiki .

https://github.com/zsiki/GeoEasy/blob/b1bd171039274157195c0742b4db28445ad28173/src/geo_easy.tcl#L104
Not used. I have searched and cannot find where this is used. Tell me?

**Comment by zsiki** [comment]
loadgeo.tcl line 186.

**Comment by zvezdochiot** [comment]
Hi @zsiki .

I could not figure it out completely, but I trust you.
