### ISSUE TITLE
Converter?

### ISSUE THREAD

**Issue by zvezdochiot** [zsiki/GeoEasy#166]
Hi @zsiki .

Maybe add a "Converter" utility to convert files without loading into the base module? Place next to ComEasy?

It would be a very convenient and more efficient use of the existing code.

**Comment by zsiki** [comment]
New command line switch can solve it. Adding the new --exp _format_ to the command line together with --nogui switch will be my answer to this issue. For example to convert coordinates from geo format to csv use the following command:
./geo_easy.tcl --nogui --exp csv --log stderr demodata/*.geo

--nogui redirects GUI messages to log file and exit GeoEasy after processing the command line
--exp _format_ exports the files given in the command line to the _format_ in the same directory (geo, are, job, wld, gsi, scr,sdr,210, nik,csv,itr, txt, gpx, dmp, kml, sql, and dxf formats are supported
--log stderr redirects log messages to the standard error
demodata/*.geo input files to convert

Note:
in case of dxf input files the texts from any layer will be converted into point, th point ID will be the text and the point code will be the DXF layer name. Double texts will be skipped without warnings.

Note:
on Windows you cannot use wildcards in file names

**Comment by zvezdochiot** [comment]
Hi @zsiki .

Excellent! It is advisable to update man. 

PS: I will leave the issue open for updating the documentation.

**Comment by zsiki** [comment]
I've created a new wiki page:
https://github.com/zsiki/GeoEasy/wiki/Using-GeoEasy-as-a-data-converter-from-the-command-line

**Comment by zsiki** [comment]
Man page also updated by https://github.com/zsiki/GeoEasy/commit/66d0703fc7e38cd43810a1695faccb74497d1d9e
