### ISSUE TITLE
Find error?

### ISSUE THREAD

**Issue by zvezdochiot** [zsiki/GeoEasy#168]
Hi @zsiki .

In some programs there is such a mechanism: one measurement is turned off and a list of errors of the unit of weight is displayed. At the end, a measurement is output , the disconnection of which leads to the minimum error of the unit of weight.

Can you add such a feature to GeoEasy?

PS: An example of a program that implements this: RGS (http://mykaralw.narod.ru/download/exe/rgsdemo-4-0-0.zip). Example of RGS report: https://github.com/Geo-Linux-Calculations/geodesist.ru-attach/threads/72942/992622-gnu-gama-3st-2K-del-ST1-M5-KP-3D.zip (uzip://gnu-gama-3st-2K-del-ST1-M5-KP-3D/rgs-4.0.0/20210207-CN-3st-2K.RgsRep.FindError.log)

PS2: It is advisable to do this as a separate module.

**Comment by zsiki** [comment]
In the "Residuals and analysis of observations" section of the GNU Gama text output the e-obs column estimates the real error of observation. It is not exactly what you wish, but it can be used similar way (see 5.8 chapter in GNU Gama documentation). 
At the beginning of the GNU Gama text output there is information of the change of mean error of unit weight, see 
"Maximal decrease of m0’’/m0 on elimination of one observation:"

**Comment by zvezdochiot** [comment]
Hi @zsiki .

I know about GNU Gama. But in the same archive in the log-files it can be seen that the obvious error found in RGS is simply ignored by GNU Gama. I decided to find an alternative analyzer. But no, so no.

**Comment by cepek** [comment]
Hmm, I have no idea what you are talking about. Can you explain to me?
Aleš

**Comment by zvezdochiot** [comment]
Hi @cepek .

In the RGS system there is such a mechanism: error search. The list of measurements, at each step only one measurement is turned off and the network is renegotiated. The list "measurement - [pvv]" is returned. At the end of the list: "measurement - min [pvv]".

**Comment by cepek** [comment]
I do not know what RGS system means
a.

**Comment by zvezdochiot** [comment]
Hi @cepek .

[RGS](http://mykaralw.narod.ru/download/exe/rgsdemo-4-0-0.zip) is a program from company "РУМБ" (Russia) under Windows for adjusting geodesic networks.

**Comment by cepek** [comment]
I see, thanks. Can you compare adjustment xml results from gama with РУМБ?
I could possibly write a conversion to some format of РУМБ (if available
... same for gama input data; actually I am working on a new version with
--export input data to be available in qgama GUI).
If I get you right, РУМБ enables iterative removal of detected observations
(something like the worst, most influential, outlayer, one in each step).
This might be tempting, but this is not a good idea in general, it must be
the expert user to analyze the adjusted data and decide what the problem is.
Aleš

**Comment by zvezdochiot** [comment]
Hi @cepek .

Ok. I can't run wine 32 bit on Debian 64 bit (I'll have to clutter up the whole system, I don't want to, maybe later).

**Comment by cepek** [comment]
Just an idea. Do not bother yourself, it's not neither urgent nor important
Aleš
