### ISSUE TITLE
step by step issue

### ISSUE THREAD

**Issue by gumimajom** [zsiki/GeoEasy#172]
Hi,

i'm trying to understand the logic of this application... Not so easy :D

By doing the steps of [step_by_step](https://github.com/zsiki/GeoEasy/blob/master/doc/step_by_step.rst) guide, i'm always hanging out on point 5001.  How and when did you calculate the final coordinates and bearing of it? With the preliminary coordinates i can' t make the traverse.
I haven't tried the rest...

thx (and sorry for my terrible english)

**Comment by zsiki** [comment]
I have added a new note to the Step by Step guide to cal calculate the coordinates of 5001 and 5002 before the traversing.

**Comment by gumimajom** [comment]
Köszönöm! 👍 
BUÉK!
