### ISSUE TITLE
Flathub listing

### ISSUE THREAD

**Issue by ovari** [zsiki/GeoEasy#174]
Please add GeoEasy to [Flathub](https://flathub.org/).

What do you think?

Thank you

**Comment by zsiki** [comment]
Sorry to answer your issue so late. I am not familiar with flatpack, could you help me to add GeoEasy?

**Comment by ovari** [comment]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by zsiki** [comment]
Nothing done,
