### ISSUE TITLE
Nikon RAW support is incomplete

### ISSUE THREAD

**Issue by XRolland** [zsiki/GeoEasy#181]
Hi, 
Nikon RAW fails to open with warning message:
`Error in data file 10 Path/FileName.RAW`

Experimented with 
- GeoEasy 3.2.1 32 and x64 (portable) on Win 11

Note:
- GeoEasy 3.2.0 seems note te be able to open Nikon RAW. It wa added by the fix #154 (comit ) #76cb7f6e1dae8eaccebb2e2ab0104974180f703b.

**Comment by XRolland** [comment]
[StBonnet FP T3.RAW.txt](https://github.com/zsiki/GeoEasy/files/9754763/StBonnet.FP.T3.RAW.txt)

**Comment by XRolland** [comment]
it shoud be relative to https://github.com/zsiki/GeoEasy/issues/154#issuecomment-1002146686:
_"Actually Metres, DDDMMSS, Zenith and NEZ coordinate order is supported. Otherwise the file is not loaded."_

In my file:
```
CO,Dist Units: Metres
CO,Angle Units: Gons
CO,Zero azimuth: North
CO,Zero VA: Zenith
CO,Coord Order: ENZ
CO,HA Raw data: Azimuth
```
-> I rename the issue as : "_Nikon RAW support is incomplete"_

**Comment by zsiki** [comment]
I need help to complete the Nikon RAW support.  So far I have seen Nikon RAW files with DDDMMSS format only. Can you send me a file with other units?

**Comment by zsiki** [comment]
Gons and ENZ have been added to Nikon RAW format. It is still an incomplete solution.
There is no instrument height for free station (resection).

**Comment by XRolland** [comment]
> There is no instrument height for free station (resection).

OK, I understand better what I've seen:
![image](https://github.com/zsiki/GeoEasy/assets/16253809/b7c796aa-b6f4-4b01-8b85-2a7e60bd9508)

Is it due to gon units or is it a new issue to create?

**Comment by zsiki** [comment]
@XRolland , I think it is not an issue. In the file you shared me (StBonnet.FP.T3.RAW.raw) all station records have 0.000 in the instrument height field.

`ST,A.0906.1,,C.1,,0.000,20.3116,20.3118`
`                              -------`
