### ISSUE TITLE
Total station data formats

### ISSUE THREAD

**Issue by rubberm0nkey** [zsiki/GeoEasy#182]
Hi,

ae04dcc0133fb94e8f309324e606897271b1b146

I'm wondering how commonly used formats these are... for example geodimeter doesn't exist anymore, foif uses fieldgenius on newest instruments, etc

What are the most commonly used data formats today?
Trimble?
Leica?
Geomax?
Sokkia?
Nikon?
Topcon?
Stonex?
Ruide?
Foif?
South?

Or the postprocessing is not a thing anymore, everything is calculated on the field? Some instruments has a built in android tablet, which competes with a computer.

**Comment by zvezdochiot** [comment]
Hi @rubberm0nkey .

This is a duplicate #64 .

**Comment by zsiki** [comment]
Why should we delete older formats?
Trimble 55xx series total stations use Geodimeter format.

**Comment by zsiki** [comment]
I usually write driver/loader for total station formats what I meet or I am asked to support.
Nowadays I mostly use SDR33, M5 and GSI. If I need only coordinates I use also CSV.
Are you satisfied with idex loader of GeoEasy? I couldn't test it much.

**Comment by faludiz** [comment]
Hi All,

The total station data formats are hell. The main problem is that, there is no standards like dxf or shp. Every manufacturer has one or more own format which changes regularry with new isntruments. 
For example leica gsi is a nightmare: sometimes the station data mingled with measurements, somtimes completely missing.
Perhaps the SDR33 or RW5 format is a quasistandard, although they also have dialects.
Interesting fact: there was a hungarian software called GeoProfi whose .mjk format was implemented as an export format by some instrument distributors for their intruments. This format was easily read by post-processing programs developed in Hungary, and is even read by [GeoEasy](https://github.com/zsiki/GeoEasy), [GeoZseni](http://geozseni.hu/), [GeoCalc](http://geocalc.hu/). 
So in Hungary, [GeoProfi .mjk](https://github.com/zsiki/GeoEasy/tree/master/src/tsdata/geoprofi) is a quasi-standard format.

**Comment by zsiki** [comment]
DXF and SHP are neither internation nor national standard,  They are industry standard ruled by a the owner (Autodesk and ESRI). To tell you the truth DXF is also a nightmare. But it is far from the topic of this discussion.
