### ISSUE TITLE
Can't resize the observations and the coordinates window

### ISSUE THREAD

**Issue by rubberm0nkey** [zsiki/GeoEasy#183]
Both of them shows only 20 lines of data.
I think it's optimized for smaller screens.
How can i change the window size? With mouse it is impossibe.

**Comment by zsiki** [comment]
Unfortunately you can't resize field-book and coordinate lists windows. There are other (less comfortable) methods to do this.
To change the number of rows for an open window, select Commands / Number of rows and change the value. It will be used till the window is open. If you would like to change the number of rows permanent, select File / Other parameters from the main window (with rotating Earth) and change Number of rows in maks. It will be used for all newly opened window in the actual session. Save parameters to make your change to all future sessions.
Alternative permanent change for the number of rows is to edit geo_easy.msk file and change the row
``set maskRows {20}``

To change width of the fields you have to edit geo_easy.msk and change the geoMaskWidths row for the mask definition.
