### ISSUE TITLE
Error when saving parameters

### ISSUE THREAD

**Issue by MrClock8163** [zsiki/GeoEasy#189]
After opening a .geo file through the file association on windows, the parameters cannot be saved due to a file path error.
![image](https://user-images.githubusercontent.com/48679831/225457535-63982c80-3cf8-4aa5-9684-944b321a58bb.png)
(Maybe because then the working directory is the directory of the opened file, and not the install directory of GeoEasy, so a relative path does not work?)

The issue is not present when trying to save the parameters after opening GeoEasy alone.

OS: Windows 10
GeoEasy version: 3.2.2dev

**Comment by zsiki** [comment]
You are right, the current directory cause the error message.
I'll correct it.

**Comment by zsiki** [comment]
Start up directory corrected and the log message added for loaded data file from command line.
A new development release will be created soon...

**Comment by zsiki** [comment]
New binary releases of the development version are available on  http://digikom.hu/english/geo_easy_e.html
