### ISSUE TITLE
ComEasy as standalone app

### ISSUE THREAD

**Issue by rubberm0nkey** [zsiki/GeoEasy#191]
I've tried to run ComEasy as separate app, but it not worked.
At first with the `make ComEasy` command created me an executable with freewrap: *ComEasy*
It was not very clear that freewrap was also needed, but the makefile helped me out :D

After i started it, i got some error messages:
- missing triangle
- missing gama-local
- missing cs2cs
- missing com_easy.hun

Finally, it started but not the *ComEasy* but the **GeoEasy**(!). Ater clicking all error messages the program quits.

**Comment by zsiki** [comment]
Thanks for your bug report.
The support for ComEasy was not in the focus after changing the GeoEasy license to GPL. ComEasy is integrated into GeoEasy, I havn't met recently any user who uses standalone ComEasy. There is no separate installation package for it, even the Windows installer doesn't contains ComEasy.exe.
I made a quick change in maincom_easy.tcl to start with the English GUI. If you would like to use it with other language, please start GeoEasy.
Do you use Linux?

**Comment by zsiki** [comment]
Thanks for your feed back.
