### ISSUE TITLE
naming conventions and eferences for localization wiki page

### ISSUE THREAD

**Issue by XRolland** [zsiki/GeoEasy#198]
Is it possible to add on on the [localization wiki page](https://github.com/zsiki/GeoEasy/wiki/How-to-localize-GeoEasy-to-my-mother-tongue%3F) :

- [x] a reference or a naming convention for the localization name length : 2 or 3 character or whatever you want
- [x] a reference or a naming convention for the localization name with region name : "en-us" or "en"
- [x] a reference for the Windows language code
- [x] all in lower case or case unsensitive?

Thanks in advance!

**Comment by zsiki** [comment]
Thanks for your tips. Localization wiki page updated.
