### ISSUE TITLE
Error "Invalid command name 'GeoFontSelect'" using the "Font…" menu

### ISSUE THREAD

**Issue by XRolland** [zsiki/GeoEasy#199]
In the main menu:
`Window > Log window`

In the Log window, or in Console Window (same error occurs):
`File > Font ...`

You get:
>   Application error
>   Error:invalid command name "GeoFontSelect"

Details:
>   invalid command name "GeoFontSelect"
>   invalid command name "GeoFontSelect"
>     while executing
>   "GeoFontSelect"
>     (menu invoke)

After closing the error window, GeoEasy is still usable.

Happened on Windows Portable, with releases 3.2.2 and 3.2.3dev_20240428.

**Comment by XRolland** [comment]
It seems that the command is called [here](https://github.com/zsiki/GeoEasy/blob/3812fec9226b7feaec6e68d41b12d85e5e36efb4/src/maskgeo.tcl#L951) but that it doesn't exist elsewhere.
And also, it's only called on [non-unix platform](https://github.com/zsiki/GeoEasy/blob/3812fec9226b7feaec6e68d41b12d85e5e36efb4/src/maskgeo.tcl#L948).

Maybe the easier is to comment the code block, waiting for the implementation of the command?

**Comment by zsiki** [comment]
The fast solution would be your proposal, to remove font change option. Somehow I lost the GeoFontSelect proc :(. As I work on Linux I haven't noticed this bug.
Is it important feature to change font?

**Comment by XRolland** [comment]
No need for me.
Maybe for little display ?

Another way of dealing with it could be to keep only the menu entry with something as "Font… (to do"). Not very elegant but if someone need it may be he'll ask for it. Or he'll code it.
