### ISSUE TITLE
Line number shoud be displayable in the observations window

### ISSUE THREAD

**Issue by XRolland** [zsiki/GeoEasy#202]
When you load a fieldbook, you can read warning messages in the log windows, as fox example:
` Repeated point for a station 1379 at line 385`

But when you look at the observations, there's no column with line number.

I tried all the masks, but none of them shows the line number.

It  could be useful when you have big jobs.

An alternative may be to activate the line in observation window when you click on the line in the log window... but I suppose it's harder to implement.

**Comment by zsiki** [comment]
@XRolland you can see the actual line number and the total at the status line of observations and coordinates windows, but it is not the same value what you get in the warning. The line number in the warning refers to the source file. There may be skipped lines depending on the type of source file. For example if you have observations in face left and right, GeoEasy will calculate average of observations during load.

This message is sent if the same target ID present in the observations from the same station, but the horizontal angle and zenith angle do not match to calculate average.

**Comment by XRolland** [comment]
Thanks @zsiki for your answer. I'm used to using software where the line number is indicated at the beginning of the line. So I stupidly didn't think to look in the status bar! Even it's not always exactly the good number, it's widely usable.

When you say 
> The line number in the warning refers to the source file.
you refer to the raw file from the total station?

And the row number in the status bar is the same as in the GEO file?

**Comment by zsiki** [comment]
@XRolland, the row number in the status line is the same as the line number in the GEO file.
In case of an error reading field-book from different sources (GSI, SDR, stb.), the line number in the popup message box refers to the line number in the source (raw) file

**Comment by XRolland** [comment]
OK, I did some tests to understand. 

- When GeoEasy read raw file, the warning messages that I got always refers to point id, and never to the line number.
- After loading raw file, if I ask to check fieldbook,  line numbers seem refers to status bar, or to the GEO file if I save it. 

So finally, everything is good for me at the moment with the line number, even if it could be easier to find one if there was a column that you can enable in a mask, maybe. But nothing insurmountable.

In another hand, maybe the message should be 
  `Repeated point %s for a station at line %s`
because the given number is the point one, and not the station one.

**Comment by zsiki** [comment]
I updated the message in the message file, see https://github.com/zsiki/GeoEasy/commit/3b286a154ae1305aa4e3906975d31284ae908dd5

Thanks!

**Comment by XRolland** [comment]
Thanks for this fix!
