### ISSUE TITLE
OLS YXH

### ISSUE THREAD

**Issue by zvezdochiot** [zsiki/GeoEasy#29]
There is an effective OLS YXH method.
I can describe this method, but I do not know how to implement it without breaking everything else.
In TCL i did not write before.

**Comment by zsiki** [comment]
An iterative solution is implemented in GeoEasy for  best fitting 3D lines based on the parametric equation of line.
Do you mean this by OLS YXZ method?

**Comment by zvezdochiot** [comment]
No. OLS YXH was developed as a method that corresponds to modern instruments (electronic total stations). He does not use the "Theory of errors in geodetic measurements", but uses directly "Theory of Probability".
This method eliminates the defects not only of the "Survey Geodetic Resection", but of the entire geodetic web.
I switched to the post-use use of this method from 2015 onwards and never failed me. Unlike the old methods of equalization.

**Comment by zvezdochiot** [comment]
Brief description of the method:
https://github.com/zvezdochiot/GeoEasy/blob/master/doc/OLS_YXH/Karetin_AN-2016-Geometry_with_errors-Google_translate.pdf

Working tables with implementation (! Contain several plugins):
https://github.com/zvezdochiot/GeoEasy/tree/master/doc/OLS_YXH/samples

**Comment by zvezdochiot** [comment]
See also https://github.com/zvezdochiot/geofindkey
