### ISSUE TITLE
SVG output from graphic window

### ISSUE THREAD

**Issue by zsiki** [zsiki/GeoEasy#30]
New export format from graphic windows to save into SVG file

**Comment by edips** [comment]
Hi. Is it possible to import or export SVG vector with Proj4? It can include coordinates like kml or dxf? I assumed SVG doesn't include coordinate system.

**Comment by edips** [comment]
Yes Proj is used for SRS. I didn't know GDAL supports SVG. 
I searched if SVG can be imported to QGIS, but I saw it is not possible to import SVG with coordinate system. It can be imported but we need to digitize it to set SRS. I will search SVG again with GDAL. Thanks.

**Comment by zvezdochiot** [comment]
Why only vector export? The raster is also useful.

**Comment by zsiki** [comment]
Extended svg output (similar to dxf export) added. Thanks @zvezdochiot for the tip o store original coordinates in svg.
Line work and contour lines are not ready
