### ISSUE TITLE
volume difference error

### ISSUE THREAD

**Issue by takacsbence** [zsiki/GeoEasy#36]
When trying to calculate the volume difference between two Digital Terrain Modells, en error message appears:

can't read "terep_toltes_ele(1)": no such element in array
can't read "terep_toltes_ele(1)": no such element in array
    while executing
"set ${tin}_ele($i)"
    (procedure "tin2grid" line 33)
    invoked from within
"tin2grid $gridname1 $gridDX $xmi $ymi $xma $yma"
    (procedure "GeoVolumeDif" line 32)
    invoked from within
"GeoVolumeDif"
    (menu invoke)

**Comment by zsiki** [comment]
Probably you have changed the triangles manually. If I recreate the DTMs from the points, there is no error.
I suppose the error comes from the swap triangles.

**Comment by zsiki** [comment]
Fixed by https://github.com/zsiki/GeoEasy/commit/3d59fa201396419323ab3760cf1bca86c600d60c
