### ISSUE TITLE
Load GSI

### ISSUE THREAD

**Issue by tlero** [zsiki/GeoEasy#4]
Hi, GeoEasy doesn't seem to be reading my GSI files. Is there any known issue?
Thanks,
Thomas

**Comment by zsiki** [comment]
No known issue about GSI. Can you send a sample which is not read by GeoEasy?
Stations are a bit tricky in GSI. GeoEasy can handle two solutions:
1. code block marks start of station

```
410001+00000002 42....+00000500 43....+00001500 44....+00001600
110002+00000121 21.104+08916180 22.104+09036240 31..00+00187101 110003+00000123 21.104+24
```
2. station height
```
110001+00000500 88.104+00001500 
110002+00000121 21.104+08916180 22.104+09036240 31..00+00187101 110003+00000123 21.104+24
```

**Comment by tlero** [comment]
Hi Zoltan,


Attached, GSI.



I've tried with removing the stars and first section. Could it be because GeoEasy only reads GSI-8 format?



Regards,



Thomas


De : Zoltan Siki <notifications@github.com>
À : zsiki/GeoEasy <GeoEasy@noreply.github.com>
Objet : Re: [zsiki/GeoEasy] Load GSI (#4)
Date : 23/01/2018 22:51:35 CET
Copie à : tlero <thomas.leroy@netcourrier.com>;
   Author <author@noreply.github.com>

No known issue about GSI. Can you send a sample which is not read by GeoEasy?
Stations are a bit tricky in GSI. GeoEasy can handle two solutions:

1- code block marks start of station 
410001+00000002 42....+00000500 43....+00001500 44....+00001600
110002+00000121 21.104+08916180 22.104+09036240 31..00+00187101 110003+00000123 21.104+24

1- station height 
110001+00000500 88.104+00001500 
110002+00000121 21.104+08916180 22.104+09036240 31..00+00187101 110003+00000123 21.104+24

**Comment by zsiki** [comment]
Hi Thomas,

I can't  find your attachment. Could you send it to my email address siki@agt.bme.hu

Do not remove starts at the beginning of lines. GeoEasy reads both GSI-8 and GSI-16.

Thanks,
Zoltan

**Comment by zsiki** [comment]
Thomas, I checked your GSI file, there are some extra data in it what GeoEasy can't handle.
I have created a GeoEasy compatible version of your file and I attached.
I had to rename it to _.txt_ becase GitHub reject _.gsi_ files please rename it back to .gsi before loading to GeoEasy.
I've edit a lot on your file, you can compare it to the original.
What we can do with your file?

Solution 1
Edit the format file or create a new format file on your instrument to follow the requirements of GeoEasy.

Solution 2
Let's revise GeoEasy source code to be able to read this type of files (and of course the "simple" gsi files).
 
[TANK_geoeasy.txt](https://github.com/zsiki/GeoEasy/files/1660112/TANK_geoeasy.txt)

**Comment by tlero** [comment]
Zoltan,


Many thanks for your time. I'll have a look at all this and see if I can tweak the GSI output from my instrument. Obviously, getting rid of all 70s codes could be an issue because the geocoding will disappear.

Thanks again.



Thomas


De : Zoltan Siki <notifications@github.com>
À : zsiki/GeoEasy <GeoEasy@noreply.github.com>
Objet : Re: [zsiki/GeoEasy] Load GSI (#4)
Date : 24/01/2018 15:29:04 CET
Copie à : tlero <thomas.leroy@netcourrier.com>;
   Author <author@noreply.github.com>

Thomas, I checked your GSI file, there are some extra data in it what GeoEasy can't handle.
I have created a GeoEasy compatible version of your file and I attached.
I had to rename it to .txt becase GitHub reject .gsi files please rename it back to .gsi before loading to GeoEasy.
I've edit a lot on your file, you can compare it to the original.
What we can do with your file?

Solution 1
Edit the format file or create a new format file on your instrument to follow the requirements of GeoEasy.

Solution 2
Let's revise GeoEasy source code to be able to read this type of files (and of course the "simple" gsi files).

TANK_geoeasy.txt

**Comment by zsiki** [comment]
Only 71 code is accepted from remarks by GeoEasy (actually). Other remark codes are skipped, but in your original file remark fields are ill formatted. See here: http://uksurveyingequipment.com/pdf/leica-flexline-gsi-manual.pdf.
Instead of 
`71....                `  
it should have been
`71....+0000000000000STN`

You can edit the format files on a computer (with Leica Geo Office, Leica SurveyOffice) and upload them to the instrument.

**Comment by tlero** [comment]
Thanks again for your involvement, Zoltan.
I'll check and modify the output gsi template.

Regards,

Thomas

---- Message d'origine ----

**Comment by hblGP** [comment]
I know this is an old issue, and it has been resolved. I've created a formatfile for Leica totalstations, that got the correct format and has worked for me. See attached file (rename so the ending is .FRT)
[GSI_GeoEasy.txt](https://github.com/zsiki/GeoEasy/files/6434090/GSI_GeoEasy.txt)

**Comment by zsiki** [comment]
Thanks!
