### ISSUE TITLE
cad4tcl

### ISSUE THREAD

**Issue by zsiki** [zsiki/GeoEasy#44]
Using cad4tcl SVG files can be displayed and PDF export is also available.
Let's test it for use in GeoEasy.

**Comment by zvezdochiot** [comment]
![LibreCAD](doc/wiki_images/multilinework3.png "LibreCAD")

May still be better to use SVG ([cad4tcl](https://cad4tcl.sourceforge.io/))?

**Comment by zsiki** [comment]
Wrong idea, the result is usually edited by surveyors and planners.

**Comment by zvezdochiot** [comment]
@zsiki say> the result is usually edited by surveyors and planners.

But not LibreCAD! AutoCAD or NanoCAD or DraftSight or BricsCAD.

LibreCAD and QCAD are not usable, SVG is better then.

**Comment by zsiki** [comment]
DXF is a common format for many CAD programs, among others: LibreCAD, AutoCAD, BricsCAD, ...). SVG is good to insert graphics in an HTML page or a documentation, that was the idea when I started this issue.

**Comment by zvezdochiot** [comment]
```
(LibreCAD or QCAD) != (AutoCAD or NanoCAD or DraftSight or BricsCAD).
```
