### ISSUE TITLE
Hiba a magassági és vízszintes tranformációnál

### ISSUE THREAD

**Issue by csabiegeto** [zsiki/GeoEasy#63]
Magassági és vízszintes transzformációnál ha kérjük a koordináták mentése file-ba opciót, akkor a célállományban a nem transzformált adat (vízszintes transzformációnál a magasság, magassági transzformációnál a vízszintes koordináták) minden transzformált pont esetén megegyezik.
Verzió: 3.0.3 dev (2018.08.30)

**Comment by zsiki** [comment]
Nem sikerült reprodukálnom a hibát, majd mutasd meg.
