### ISSUE TITLE
non-numeric string

### ISSUE THREAD

**Issue by MIZS** [zsiki/GeoEasy#78]
can't use non-numeric string as operand of "+"
can't use non-numeric string as operand of "+"
    while executing
"expr {$entryRow($w) + 1}"
    (procedure "LastVal" line 9)
    invoked from within
"LastVal .cargo_ap_geo__coo.grd.e1-0"
    (command bound to event)

**Comment by zsiki** [comment]
https://github.com/zsiki/GeoEasy/commit/33f92bf3e3a29134e722620273754d9892d6710e commit tries to avoid error message.
