### ISSUE TITLE
sdr33: ComEasy vs stty

### ISSUE THREAD

**Issue by zvezdochiot** [zsiki/GeoEasy#99]
Sokkia Set data read using ComEasy and stty/cat is very different.
Details will be given later.

**Comment by zvezdochiot** [comment]
Linux debian 3.16.0-0.bpo.4-686-pae #1 SMP Debian 3.16.39-1+deb8u1~bpo70+1 (2017-02-24) i686 GNU/Linux.

Data from the device through a SF flashcard:
https://github.com/Geo-Linux-Calculations/GeoEasy/blob/master/src/tsdata/sdr33/SHM-P13N.CRD

Data from the device through the cord + topocad:
https://github.com/Geo-Linux-Calculations/GeoEasy/blob/master/src/tsdata/sdr33/SHM-P13N-topocad.sdr

Data from the device through the cord + stty/cat:
https://github.com/Geo-Linux-Calculations/GeoEasy/blob/master/src/tsdata/sdr33/SHM-P13N-stty.sdr

Data from the device through the cord + GeoEasy/ComEasy:
https://github.com/Geo-Linux-Calculations/GeoEasy/blob/master/src/tsdata/sdr33/SHM-P13N-comeasy.sdr

**Comment by zsiki** [comment]
The differences are not significant. All data sets can be loaded into GeoEasy.

Differences are in code page: 
the name of the month in the date (first, fifth and sevens rows),
the comment in the third row

EOL character differences DOS (cr/lf) versus Linux (lf). That is the reason to have different number of bytes.

Data from the flash card have trailing spaces instead of zeros, no difference in the value.

**Comment by zvezdochiot** [comment]
Files received using GeoEasy cannot be sent back to the device!

**Comment by zsiki** [comment]
It is not common to send back the downloaded data to the instrument. I've never uploaded observations to the instrument. There is a Save as in the File menu to export coordinates to instrument formats (including sdr format). Did you try it?

**Comment by zvezdochiot** [comment]
GeoEasy: "Save as" (LIN:UTF8) [17074]:

https://github.com/Geo-Linux-Calculations/GeoEasy/blob/master/src/tsdata/sdr33/shm-p13n-comeasy-saveas.sdr

Wrong line ending = Cannot send to device.

**Comment by zsiki** [comment]
unix2dos or u2d, total stations use dos like end of line (cr+lf)

**Comment by zsiki** [comment]
Did you try to set EOL marker in the communication parameters dialog? Change "auto" to "crlf" or after dos2unix try the "binary".

**Comment by zvezdochiot** [comment]
Ok. I will try.
